version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run: npm install
      - run: npm run build
      - run: npm run deploy
