name: Node CI

on:
  push:
    branches:
      - master
      - sromain/test-job-release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build
          npm test
        env:
          CI: true
      - name: NPM publish if not present
        uses: romainseb/action-npm-publish-if-not-present@0.0.1
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
